metadata_from_days_ago: 60
metadata_datasets:
- datasetName: LANDSAT_8_C1
  fieldId: fieldId
  datasetFilterType: and
  fields:
  - fieldName: WRS Path
    fieldFilterType: between
    fieldValues:
      - value: 13
      - value: 33
  - fieldName: WRS Row
    fieldFilterType: between
    fieldValues:
      - value: 33
      - value: 43
  metadataFields:
  - field:
    - fieldName: Landsat Scene Identifier
      databaseFieldName: scene_id
      method: api
  - field:
    - fieldName: Landsat Product Identifier
      databaseFieldName: landsat_product_id
      method: api
  - field:
    - fieldName: Collection Category
      databaseFieldName: collection_category
      method: api
  - field:
    - fieldName: OLI_TIRS
      databaseFieldName: sensor
      method: constant
  - field:
    - fieldName: Acquisition Date
      databaseFieldName: acquisition_date
      method: api
  - field:
    - fieldName: url
      databaseFieldName: browse_url
      method: api_browse
  - field:
    - fieldName: WRS Path
      databaseFieldName: path
      method: api
  - field:
    - fieldName: WRS Row
      databaseFieldName: row
      method: api
  - field:
    - fieldName: Scene Cloud Cover
      databaseFieldName: cc_full
      method: api
  - field:
    - fieldName: 0
      databaseFieldName:  cc_quad_ul
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_ur
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_ll
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_lr
      method: constant
  - field:
    - fieldName: Data Type Level-1
      databaseFieldName: data_type_l1
      method: api
  - field:
    - fieldName: 999999
      databaseFieldName: l1_key
      method: constant
- datasetName: LANDSAT_ETM_C1
  fieldId: fieldId
  datasetFilterType: and
  fields:
  - fieldName: WRS Path
    fieldFilterType: between
    fieldValues:
      - value: 13
      - value: 33
  - fieldName: WRS Row
    fieldFilterType: between
    fieldValues:
      - value: 33
      - value: 43
  metadataFields:
  - field:
    - fieldName: Landsat Scene Identifier
      databaseFieldName: scene_id
      method: api
  - field:
    - fieldName: Landsat Product Identifier
      databaseFieldName: landsat_product_id
      method: api
  - field:
    - fieldName: Collection Category
      databaseFieldName: collection_category
      method: api
  - field:
    - fieldName: LANDSAT_7
      databaseFieldName: sensor
      method: constant
  - field:
    - fieldName: Acquisition Date
      databaseFieldName: acquisition_date
      method: api
  - field:
    - fieldName: url
      databaseFieldName: browse_url
      method: api_browse
  - field:
    - fieldName: WRS Path
      databaseFieldName: path
      method: api
  - field:
    - fieldName: WRS Row
      databaseFieldName: row
      method: api
  - field:
    - fieldName:  Scene Cloud Cover
      databaseFieldName: cc_full
      method: api
  - field:
    - fieldName: 0
      databaseFieldName:  cc_quad_ul
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_ur
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_ll
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_lr
      method: constant
  - field:
    - fieldName: Data Type Level-1
      databaseFieldName: data_type_l1
      method: api
  - field:
    - fieldName: 999999
      databaseFieldName: l1_key
      method: constant
- datasetName: LANDSAT_TM_C1
  fieldId: fieldId
  datasetFilterType: and
  fields:
  - fieldName: WRS Path
    fieldFilterType: between
    fieldValues:
      - value: 13
      - value: 33
  - fieldName: WRS Row
    fieldFilterType: between
    fieldValues:
      - value: 33
      - value: 43
  metadataFields:
  - field:
    - fieldName: Landsat Scene Identifier
      databaseFieldName: scene_id
      method: api
  - field:
    - fieldName: NA
      databaseFieldName: landsat_product_id
      method: constant
  - field:
    - fieldName: Collection Category
      databaseFieldName: collection_category
      method: api
  - field:
    - fieldName: LANDSAT_4-5
      databaseFieldName: sensor
      method: constant
  - field:
    - fieldName: Acquisition Date
      databaseFieldName: acquisition_date
      method: api
  - field:
    - fieldName: url
      databaseFieldName: browse_url
      method: api_browse
  - field:
    - fieldName: WRS Path
      databaseFieldName: path
      method: api
  - field:
    - fieldName: WRS Row
      databaseFieldName: row
      method: api
  - field:
    - fieldName:  Scene Cloud Cover
      databaseFieldName: cc_full
      method: api
  - field:
    - fieldName: 0
      databaseFieldName:  cc_quad_ul
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_ur
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_ll
      method: constant
  - field:
    - fieldName: 0
      databaseFieldName: cc_quad_lr
      method: constant
  - field:
    - fieldName: Data Type Level-1
      databaseFieldName: data_type_l1
      method: api
  - field:
    - fieldName: 999999
      databaseFieldName: l1_key
      method: constant
database:
  - json_field:
    database_field:
  - json_field:
    database_field:
